apiVersion: v2
name: todo
description: Todo Example Application
type: application
version: 1.0.0
appVersion: "1.0.2"

dependencies:
- name: postgresql
  version: "15.2.2"
  repository: "oci://registry-1.docker.io/bitnamicharts"
  condition: postgresql.integrated
